# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Louis Safety, Abu Dhabi | Fire Fighting Appliances, Lifeboat, Liferaft and Automation
email: operations@louissafety.com
description: > # Established in 2001, Louis Safety - Abu Dhabi is a reliable safety service and supply partner to Marine and Oil &amp; Gas Industry. Inspections and Certification
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://louissafety.com" # the base hostname & protocol for your site
twitter_username: louissafety
github_username:  louissafety

# Build settings
markdown: kramdown
